name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      # Stap 1: Haal de code op
      - name: Checkout code
        uses: actions/checkout@v3

      # Stap 2: Installeer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      # Stap 3: Vervang placeholders in firebase.js door GitHub Secrets
      - name: Replace environment variables in firebase.js
        run: |
          sed -i "s|{{ADMIN_FIREBASE_API_KEY}}|${{ secrets.ADMIN_FIREBASE_API_KEY }}|g" js/adminfirebase.js
          sed -i "s|{{ADMIN_FIREBASE_AUTH_DOMAIN}}|${{ secrets.ADMIN_FIREBASE_AUTH_DOMAIN }}|g" js/adminfirebase.js
          sed -i "s|{{ADMIN_FIREBASE_DATABASE_URL}}|${{ secrets.ADMIN_FIREBASE_DATABASE_URL }}|g" js/adminfirebase.js
          sed -i "s|{{ADMIN_FIREBASE_PROJECT_ID}}|${{ secrets.ADMIN_FIREBASE_PROJECT_ID }}|g" js/adminfirebase.js
          sed -i "s|{{ADMIN_FIREBASE_STORAGE_BUCKET}}|${{ secrets.ADMIN_FIREBASE_STORAGE_BUCKET }}|g" js/adminfirebase.js
          sed -i "s|{{ADMIN_FIREBASE_MESSAGING_SENDER_ID}}|${{ secrets.ADMIN_FIREBASE_MESSAGING_SENDER_ID }}|g" js/adminfirebase.js
          sed -i "s|{{ADMIN_FIREBASE_APP_ID}}|${{ secrets.ADMIN_FIREBASE_APP_ID }}|g" js/adminfirebase.js
          sed -i "s|{{ADMIN_FIREBASE_MEASUREMENT_ID}}|${{ secrets.ADMIN_FIREBASE_MEASUREMENT_ID }}|g" js/adminfirebase.js

      # Stap 4: Deploy naar GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ 
          publish_branch: gh-pages
          force_orphan: true
